import numpy as np
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
from time import sleep
import sys


def remove_duplicate_place_code(df):
    df = df.drop_duplicates(['place_code'])
    df = df.reset_index()
    return df


def read_pickle_and_split_category():
    df = pd.read_pickle(f'jeju(1).pkl').drop(columns='index')

    for i in range(2, 10):
        df = pd.concat([df, pd.read_pickle(f'jeju({i}).pkl').drop(columns='index')], ignore_index=True)
    print(f"{len(df)}개 데이터를 읽어옴")

    category_list = [{"name": "문화시설", "code": "CT1"}, {"name": "관광명소", "code": "AT4"},
                     {"name": "음식점", "code": "FD6"}, {"name": "카페", "code": "CE7"}, {"name": "기타", "code": ""}]
    columns_list = ["place_code", "place_name", "category_code", "category_name", "x", "y",
                    "road_address", "place_url"]

    arr_1 = pd.DataFrame(columns=columns_list);
    arr_2 = pd.DataFrame(columns=columns_list);
    arr_3 = pd.DataFrame(columns=columns_list);
    arr_4 = pd.DataFrame(columns=columns_list);
    arr_5 = pd.DataFrame(columns=columns_list);

    for idx, ser in df.iterrows():
        print(idx)
        if ser["category_code"] == category_list[0]["code"]:
            arr_1 = pd.concat([arr_1, ser.to_frame().T], ignore_index=True)
        elif ser["category_code"] == category_list[1]["code"]:
            arr_2 = pd.concat([arr_2, ser.to_frame().T], ignore_index=True)
        elif ser["category_code"] == category_list[2]["code"]:
            arr_3 = pd.concat([arr_3, ser.to_frame().T], ignore_index=True)
        elif ser["category_code"] == category_list[3]["code"]:
            arr_4 = pd.concat([arr_4, ser.to_frame().T], ignore_index=True)
        elif ser["category_code"] == category_list[4]["code"]:
            arr_5 = pd.concat([arr_5, ser.to_frame().T], ignore_index=True)

    arr_1 = remove_duplicate_place_code(arr_1)
    arr_2 = remove_duplicate_place_code(arr_2)
    arr_3 = remove_duplicate_place_code(arr_3)
    arr_4 = remove_duplicate_place_code(arr_4)
    arr_5 = remove_duplicate_place_code(arr_5)

    arr_1.to_pickle('문화시설.pkl')
    arr_2.to_pickle('관광명소.pkl')
    arr_3.to_pickle('음식점.pkl')
    arr_4.to_pickle('카페.pkl')
    arr_5.to_pickle('기타.pkl')

    arr_1.to_excel("문화시설.xlsx")
    arr_2.to_excel("관광명소.xlsx")
    arr_3.to_excel("음식점.xlsx")
    arr_4.to_excel("카페.xlsx")
    arr_5.to_excel("기타.xlsx")

    print(len(arr_1), len(arr_2), len(arr_3), len(arr_4), len(arr_5))


def drop_by_category():
    df = pd.read_pickle(f'기타.pkl').drop(columns='index')
    category_name_list = ["문화,예술 > 미술,공예", "스포츠,레저", "여행 > 관광,명소"]

    for idx, ser in df.iterrows():
        print(idx)
        flag = False
        for i in range(0, len(category_name_list)):
            if category_name_list[i] in ser["category_name"]:
                flag = True
                break
        if flag is False:
            df.drop(idx, inplace=True)

    df.to_pickle('기타(필터링).pkl')
    df.to_excel("기타(필터링).xlsx")


def crawling_review_count(n, start, end):
    print(start, end)
    scraper = PlaceInfoScraper()
    category_list = [{"name": "문화시설", "code": "CT1"}, {"name": "관광명소", "code": "AT4"},
                     {"name": "음식점", "code": "FD6"}, {"name": "카페", "code": "CE7"}, {"name": "기타(필터링)", "code": ""}]

    comment_count_list = []
    review_count_list = []
    df = pd.read_pickle(f'{category_list[n - 1]["name"]}.pkl')[start:end]
    for idx, ser in df.iterrows():
        url = ser["place_url"]
        comment_count, review_count = scraper.get_place_info(url)
        comment_count_list.append(comment_count)
        review_count_list.append(review_count)
        print(f"{idx + 1}/{len(df)} ({comment_count}, {review_count})     {url}")
    df["comment_count"] = comment_count_list
    df["review_count"] = review_count_list

    df.to_pickle(f'{category_list[n - 1]["name"]}_new_{start}.pkl')
    df.to_excel(f'{category_list[n - 1]["name"]}_new_{start}.xlsx')


def concat_pickle(n):
    category_list = [{"name": "문화시설", "code": "CT1"}, {"name": "관광명소", "code": "AT4"},
                     {"name": "음식점", "code": "FD6"}, {"name": "카페", "code": "CE7"}, {"name": "기타(필터링)", "code": ""}]

    df = pd.read_pickle(f'{category_list[n - 1]["name"]}_new_0.pkl')
    if 'index' in df.columns:
        df = df.drop(columns='index')

    for i in range(1, 5):
        data = pd.read_pickle(f'{category_list[n - 1]["name"]}_new_{i * 1000}.pkl')
        if 'index' in data.columns:
            data = data.drop(columns='index')
        df = pd.concat([df, data], ignore_index=True)

    df.to_pickle(f'{category_list[n - 1]["name"]}_new.pkl')
    df.to_excel(f'{category_list[n - 1]["name"]}_new.xlsx')


def drop_row_by_review_count(n):
    category_list = [{"name": "문화시설", "code": "CT1"}, {"name": "관광명소", "code": "AT4"},
                     {"name": "음식점", "code": "FD6"}, {"name": "카페", "code": "CE7"}, {"name": "기타(필터링)", "code": ""}]

    df = pd.read_pickle(f'{category_list[n - 1]["name"]}_new.pkl')
    if 'index' in df.columns:
        df = df.drop(columns='index')
    new_df = pd.DataFrame()
    sum_list = []
    for idx, ser in df.iterrows():
        sum = int(ser["comment_count"]) + int(ser["review_count"])
        if sum == 0:
            continue
        sum_list.append(sum)
        new_df = pd.concat([new_df, ser.to_frame().T], ignore_index=True)
    new_df["sum"] = sum_list

    new_df.to_pickle(f'{category_list[n - 1]["name"]}_nonezero.pkl')
    new_df.to_excel(f'{category_list[n - 1]["name"]}_nonezero.xlsx')


def select_row_by_review_count(n):
    category_list = [{"name": "문화시설", "code": "CT1"}, {"name": "관광명소", "code": "AT4"},
                     {"name": "음식점", "code": "FD6"}, {"name": "카페", "code": "CE7"}, {"name": "기타(필터링)", "code": ""}]

    df = pd.read_pickle(f'{category_list[n - 1]["name"]}_nonezero.pkl')
    if 'index' in df.columns:
        df = df.drop(columns='index')
    new_df = pd.DataFrame()
    for idx, ser in df.iterrows():
        if int(ser["sum"]) < 10:
            continue
        new_df = pd.concat([new_df, ser.to_frame().T], ignore_index=True)

    new_df.to_pickle(f'{category_list[n - 1]["name"]}_select.pkl')
    new_df.to_excel(f'{category_list[n - 1]["name"]}_select.xlsx')


def count_place_by_category(n):
    category_list = [{"name": "문화시설", "code": "CT1"}, {"name": "관광명소", "code": "AT4"},
                     {"name": "음식점", "code": "FD6"}, {"name": "카페", "code": "CE7"}, {"name": "기타(필터링)", "code": ""}]
    df = pd.read_pickle(f'{category_list[n - 1]["name"]}_select.pkl')
    category_count_dic = {}
    for idx, ser in df.iterrows():
        category_name = ser["category_name"]
        if category_name in category_count_dic.keys():
            category_count_dic[category_name] = category_count_dic[category_name] + 1
        else:
            category_count_dic[category_name] = 1

    category_count_dic = dict(sorted(category_count_dic.items()))
    for key, value in category_count_dic.items():
        print(key, value)


def separation_by_category_name():
    file_list = [{"name": "문화시설", "code": "CT1"}, {"name": "관광명소", "code": "AT4"},
                 {"name": "음식점", "code": "FD6"}, {"name": "카페", "code": "CE7"}, {"name": "기타(필터링)", "code": ""}]

    df = pd.DataFrame()
    drop_ser = pd.DataFrame()
    category_list = ["맛집", "카페/간식", "액티비티/체험", "스포츠/레저", "전시", "휴양"]
    subcategory_list = [[], [], [], [], [], []]
    subcategory_list[0] = {
        "한식": ["기사식당", "도시락", "한식", "감자탕", "곰탕", "국밥", "국수", "냉면", "두부전문점", "사철탕,영양탕", "설렁탕", "수제비", "순대", "쌈밥",
               "육류,고기", "갈비", "곱창,막창", "꿩,타조", "닭요리", "삼계탕", "불고기,두루치기", "삼겹살", "오리", "족발,보쌈", "주먹밥", "죽", "찌개,전골",
               "한정식", "해물,생선", "게,대게", "굴,전복", "매운탕,해물탕", "복어", "아구", "장어", "조개", "추어", "회", "해장국"],
        "일식": ["일식", "돈까스,우동", "일본식라면", "일식집", "참치회", "초밥,롤", "철판요리"],
        "중식": ["중식", "양꼬치", "중국요리"],
        "분식": ["분식", "떡볶이"],
        "양식": ["샐러드", "양식", "멕시칸,브라질", "스테이크,립", "이탈리안", "피자", "해산물", "바닷가재", "햄버거", "패스트푸드", "샌드위치"],
        "술집": ["술집", "실내포장마차", "와인바", "일본식주점", "칵테일바", "호프,요리주점"],
        "아시아": ["아시아음식", "동남아음식", "베트남음식", "태국음식", "인도음식", "터키음식"],
        "뷔페/레스토랑": ["뷔페", "고기뷔페", "한식뷔페", "해산물뷔페", "패밀리레스토랑"],
        "샤브샤브": ["샤브샤브"],
        "치킨": ["치킨"],
        "퓨전": ["퓨전요리", "퓨전일식", "퓨전중식", "퓨전한식"]}
    subcategory_list[1] = {
        "카페": ["카페", "공차", "다방", "생과일전문점", "리치망고", "쥬씨", "전통찻집", "오가다", "커피전문점", "달리는커피", "드롭탑", "메가MGC커피", "블루샥",
               "빽다방", "스타벅스", "엔제리너스", "읍천리382", "이디야커피", "커피빈", "컴포즈커피", "탐앤탐스", "투썸플레이스", "파스쿠찌", "폴바셋", "할리스",
               "팔공티"],
        "디저트": ["간식", "닭강정", "도넛", "떡,한과", "아이스크림", "제과,베이커리", "초콜릿", "디저트카페", "디저트39", "설빙"],
        "이색카페": ["테마카페", "갤러리카페", "고양이카페", "만화카페", "놀숲", "벌툰", "북카페", "애견카페", "키즈카페"]}
    subcategory_list[2] = {"승마": ["승마", "승마장"],
                           "관광농원": ["관광농원"],
                           "동물원": ["동물원", "실내동물원"],
                           "유원지/민속촌": ["유원지", "민속촌"],
                           "테마체험": ["테마파크", "카페거리", "워터테마파크", "테마거리", "먹자골목", "도자기,도예촌", "미술,공예", "도자기", "목공예", "수예,자수",
                                    "화랑", "화방"],
                           "과학": ["과학관", "천문대"]}
    subcategory_list[3] = {"골프": ["골프장"],
                           "해양": ["낚시", "낚시터", "수영,수상", "수상스포츠", "스킨스쿠버"],
                           "자전거/싸이클": ["스포츠,레저", "자전거,싸이클", "자전거대여소"]}
    subcategory_list[4] = {"박물관": ["박물관", "테디베어뮤지엄"],
                           "미술관": ["미술관"],
                           "전시관": ["전시관"],
                           "문화유적": ["문화유적", "릉,묘,총", "봉수대", "사당,제단", "산성,성곽", "생가,고택", "유적지", "탑,비석", "향교,서당", "종교유적지"],
                           "기념관": ["기념관"],
                           "공연/연극": ["공연장,연극극장"]}
    subcategory_list[5] = {"산": ["산", "산봉우리", "등산로"],
                           "오름": ["오름"],
                           "올레길": ["제주올레길"],
                           "해변": ["해수욕장,해변", "방조제", "바위"],
                           "자연생태": ["저수지", "호수", "계곡", "동굴", "연못", "폭포", "하천"],
                           "도보": ["도보여행", "숲", "둘레길", "자연휴양림", "고개", "촬영지"],
                           "수목원/식물원": ["수목원,식물원"],
                           "섬": ["섬"],
                           "공원": ["도립공원", "국립공원"],
                           "온천": ["온천"],
                           }

    exception_category_name = ["음식점", "관광,명소", "생태보존,서식지"]
    subcategory_by_place_name = {"이령": "한식",
                                 "와인도시": "양식",
                                 "광명대창집 신서귀포점": "한식",
                                 "텐더로인": "일식",
                                 "싱싱식당": "중식",
                                 "생이기정": "도보",
                                 "도구리알": "해변",
                                 "월령코지": "해변",
                                 "산양큰엉곶": "도보",
                                 "저지예술인마을": "도보",
                                 "한담해안산책로": "도보",
                                 "제주탐나라공화국": "테마체험",
                                 "화순곶자왈": "도보",
                                 "박수기정": "해변",
                                 "어음리억새군락지": "도보",
                                 "돌염전": "해변",
                                 "갯깍주상절리대": "해변",
                                 "진곶내 (폐쇄)": "해변",
                                 "선녀코지": "해변",
                                 "한라산영실": "산",
                                 "메밀꽃밭": "도보",
                                 "법환어촌계해녀체험센터": "테마체험",
                                 "속골": "자연생태",
                                 "돔베낭골": "해변",
                                 "황우지선녀탕": "해변",
                                 "동너븐덕": "해변",
                                 "소남머리": "공원",
                                 "정모시쉼터": "도보",
                                 "소천지": "자연생태",
                                 "생이돌": "해변",
                                 "닭머르": "해변",
                                 "김경숙해바라기농장": "관광농원",
                                 "조천만세동산": "공원",
                                 "관곶": "해변",
                                 "서우봉 일몰지": "해변",
                                 "위미리수국길": "도보",
                                 "태웃개": "해변",
                                 "올티스": "테마체험",
                                 "동복관광체험어장": "테마체험",
                                 "유채꽃프라자": "도보",
                                 "가시리 국산화 풍력발전단지": "도보",
                                 "제주동백마을": "도보",
                                 "김녕금속공예벽화마을": "도보",
                                 "청굴물": "해변",
                                 "송당무끈모루": "도보",
                                 "오저여": "해변",
                                 "짱구네 유채꽃밭": "도보",
                                 "유채꽃밭": "도보",
                                 "비양도망대": "해변",
                                 "청수곶자왈": "도보",
                                 "납읍난대림지역": "도보",
                                 "1100고지습지": "산",
                                 "제주농업생태원": "테마체험",
                                 "하도리철새도래지": "해변"
                                 }
    category_col = []
    subcategory_col = []
    # 5개 파일 읽어오면서 반복
    for i in range(0, len(file_list)):
        temp_df = pd.read_pickle(f'{file_list[i]["name"]}_select.pkl')
        # print(file_list[i]["name"])
        # print(temp_df)
        # 각 파일의 row 마다 category_name을 이용하여 카테고리 분류
        for idx, ser in temp_df.iterrows():
            find = False
            name = ser["category_name"].split(' > ')[-1]
            if name in exception_category_name:
                place_name = ser["place_name"]
                if place_name in subcategory_by_place_name.keys():
                    subcategory = subcategory_by_place_name[place_name]
                    for j in range(0, len(subcategory_list)):
                        if subcategory in subcategory_list[j].keys():
                            find = True
                            category_col.append(category_list[j])
                            subcategory_col.append(subcategory)
                            df = pd.concat([df, ser.to_frame().T], ignore_index=True)
            else:
                for j in range(0, len(subcategory_list)):
                    for key, value_list in subcategory_list[j].items():
                        for value in value_list:
                            if value == name:
                                find = True
                                category_col.append(category_list[j])
                                subcategory_col.append(key)
                                df = pd.concat([df, ser.to_frame().T], ignore_index=True)
            if find is False:
                drop_ser = pd.concat([drop_ser, ser.to_frame().T], ignore_index=True)

    df["category"] = category_col
    df["subcategory"] = subcategory_col

    df.to_pickle(f'전체_subcategory.pkl')
    df.to_excel(f'전체_subcategory.xlsx')
    drop_ser.to_pickle(f'drop_subcategory.pkl')
    drop_ser.to_excel(f'drop_subcategory.xlsx')

    print(df)
    print(temp_df)


def print_subcategory_count():
    df = pd.read_pickle('전체_subcategory.pkl')
    count = {"맛집": {}, "카페/간식": {}, "액티비티/체험": {}, "스포츠/레저": {}, "전시": {}, "휴양": {}}
    for idx, ser in df.iterrows():
        category = ser["category"]
        subcategory = ser["subcategory"]
        if subcategory in count[category].keys():
            count[category][subcategory] = count[category][subcategory] + 1
        else:
            count[category][subcategory] = 1
    for category in count.keys():
        print(category)
        sub_dic = dict(sorted(count[category].items()))
        for key, value in sub_dic.items():
            print(key, value)
        print()


def crawling_place_data():
    scraper = PlaceInfoScraper()
    df_file = pd.read_pickle('전체_subcategory.pkl')
    # for x in range(0, 1):
    #     df = df_file[523:524]
    #     i = "temp"
    for i in range(85, 88):
        df = df_file[i*100:(i+1)*100]
        info = pd.DataFrame()
        tag = pd.DataFrame(columns=["place_code", "tag"])
        review = pd.DataFrame(columns=["place_code", "score", "created_date"])
        img_url = []
        tag_count = []

        for idx, ser in df.iterrows():
            url = ser["place_url"]
            code = ser["place_code"]
            data = scraper.get_place_data(url)
            if data is None:
                continue

            # 태그
            data["tag"]["place_code"] = code
            tag = pd.concat([tag, data["tag"]], ignore_index=True)
            tag_count.append(data["tag"].shape[0])
            # 리뷰
            data["review"]["place_code"] = code
            review = pd.concat([review, data["review"]], ignore_index=True)
            # 이미지
            info = pd.concat([info, ser.to_frame().T], ignore_index=True)
            img_url.append(data["img_url"])
            print(
                f"[{i}] {idx}/{df_file.shape[0]} {url} 리뷰 {data['review'].shape[0]}개, 태그 {data['tag'].shape[0]}개, 이미지 {data['img_url']}")

        info["img_url"] = img_url
        info["tag_count"] = tag_count

        # print(info)
        info.to_pickle(f'전체_info_{i}.pkl')
        info.to_excel(f'전체_info_{i}.xlsx')
        # print(tag)
        tag.to_pickle(f'전체_tag_{i}.pkl')
        tag.to_excel(f'전체_tag_{i}.xlsx')
        # print(review)
        review.to_pickle(f'전체_review_{i}.pkl')
        review.to_excel(f'전체_review_{i}.xlsx')


def concat_pickle_file():
    for file_name in ["info", "tag", "review"]:
        new_df = pd.DataFrame()
        for i in range(0, 88):
            df = pd.read_pickle(f'전체_{file_name}_{i}.pkl')
            if 'index' in df.columns:
                df = df.drop(columns='index')
            for idx, ser in df.iterrows():
                new_df = pd.concat([new_df, ser.to_frame().T], ignore_index=True)

            new_df.to_pickle(f'전체_{file_name}.pkl')
            new_df.to_excel(f'전체_{file_name}.xlsx')


def print_tag_count():
    df = pd.read_pickle(f'전체_tag.pkl')
    tag_count_dic = {}
    for idx, ser in df.iterrows():
        tag = ser["tag"]
        if tag in tag_count_dic.keys():
            tag_count_dic[tag] = tag_count_dic[tag] + 1
        else:
            tag_count_dic[tag] = 1

    tag_count_dic = dict(sorted(tag_count_dic.items(), key=lambda item: item[1], reverse=True))
    for key, value in tag_count_dic.items():
        print(f'"{key}",')
    return tag_count_dic


def drop_and_rename_tag():
    info_df = pd.read_pickle(f'전체_info.pkl')
    tag_df = pd.read_pickle(f'전체_tag.pkl')
    rename_by_substring = {
        "오션뷰" : ["바다뷰"],
        "핸드드립" : [],
        "브런치" : [],
        "일출" : [],
        "포토존" : ["포토스팟"],
        "빈티지" : [],
        "베이커리" : [],
        "아이와함께" :["아이와", "어린이체험관"],
        "애견동반" : [],
        "루프탑" : [],
        "나들이" : [],
        "테라스" :[],
        "흑돼지" : [],
        "서핑" : [],
        "고기국수" : [],
        "비건" : [],
        "갈치조림" : [],
        "보말칼국수" : [],
        "수제버거" : [],
        "와인바" : [],
        "승마" : [],
        "소금빵" : []
    }

    tag_list = [
        "아침식사",
        "안심식당",
        "혼밥",
        "전통음식",
        "분위기좋은",
        "감성카페",
        "데이트코스",
        "이국적인",
        "이색카페",
        "노포",
        "건강식",
        "억새밭",
        "노키즈존",
        "칵테일바",
        "북카페",
        "앤틱한",
        "피맥",
        "경양식요리",
        "예스키즈존",
        "로컬푸드",
        "물놀이",
        "한식뷔페",
        "벚꽃명소",
        "원데이클래스",
        "실내관광지",
        "대형카페",
        "야외정원",
        "수상레저",
        "힐링카페",
        "낭만적인",
        "레트로풍",
        "걷기좋은",
        "단풍명소",
        "서핑",
        "핑크뮬리명소",
        "노펫존",
        "공방체험",
        "갤러리카페",
        "LP바",
        "다이닝펍",
        "라운지펍",
        "드라이브코스",
        "식물카페",
        "미디어아트",
        "차박",
        "녹차밭",
        "회전초밥",
        "캠핑느낌나는",
        "낮술하기좋은",
        "파스타",
        "전망좋은",
        "사진전시",
        "미술전시",
        "뮤직펍",
        "무인카페",
        "민속주점",
        "플라워카페",
        "야외전시장",
        "라이브공연",
        "보드게임카페",
        "아기자기한",
        "실내놀거리",
        "비누공방",
        "감귤체험",
        "한옥스타일",
        "캔들공방",
        "유람선",
        "와인바",
        "해장하기좋은",
        "트릭아트뮤지엄",
        "락카페",
        "체험프로그램",
        "제주도",
        "돈까스",
        "고등어회",
        "야외테이블",
        "프랑스음식",
        "드로잉카페",
        "딱새우회",
        "이자카야",
        "샌드위치",
        "지중해요리",
        "피자",
        "떡카페",
        "이색술집",
        "멕시코요리",
        "혼고기",
        "포토카페",
        "한옥카페",
        "고양이카페",
        "스노클링",
        "산책로",
        "해바라기",
        "동백꽃",
        "레일바이크",
        "몸국",
        "스페인요리",
        "고즈넉한",
        "위스키",
        "칵테일",
        "온실카페",
        "룸카페",
        "야외카페",
        "주택개조카페",
        "도자기공방",
        "카약체험",
        "스쿠버다이빙",
        "VR체험",
        "제주4.3유적",
        "딱새우",
        "스테이크",
        "어린이놀이방",
        "샐러드카페",
        "북해도식",
        "라운지카페",
        "제주에그타르트",
        "제주북카페",
        "제주서쪽카페",
        "제주감성카페",
        "만화카페",
        "제주애월카페",
        "로스터리카페",
        "공부하기좋은",
        "스콘",
        "제주공항카페",
        "종달리카페",
        "성산일출봉카페",
        "향수공방",
        "패들보드",
        "유물전시",
        "가족여행",
        "수국명소",
        "스누피가든",
        "우도",
        "한정식코스요리",
        "고사리육개장",
        "제주협재흑돼지",
        "판포포구맛집",
        "제주서쪽맛집",
        "신화월드맛집",
        "파스타맛집",
        "제주도와인바",
        "간맥",
        "보말죽",
        "제주한정식",
        "돔베고기",
        "협재술집",
        "비어카페",
        "모슬포맛집",
        "제주답례품",
        "화덕피자",
        "제주현지인맛집",
        "라이브바",
        "피쉬앤칩스",
        "서귀포이자카야",
        "사계해변",
        "뇨끼",
        "스파게티",
        "제주한림맛집",
        "한식",
        "떡볶이",
        "제주해장국",
        "제주도횟집",
        "산방산흑돼지",
        "제주도초콜릿",
        "제주여행선물",
        "송악산",
        "서귀포와인",
        "수제마카롱",
        "용머리해안맛집",
        "제주베이커리카페",
        "냉면",
        "돈까스뷔페",
        "용머리해안",
        "해물탕",
        "분식카페",
        "양념갈비",
        "데이트하기좋은",
        "오마카세",
        "애월아침식사",
        "제주아침식사",
        "우럭튀김",
        "대형주차장",
        "파인다이닝",
        "브런치맛집",
        "제주갈치조림맛집",
        "제주쌀국수",
        "제주도흑돼지",
        "중문갈치조림",
        "픽업서비스",
        "서귀포갈치조림",
        "중문흑돼지",
        "제주타코",
        "펍",
        "하이볼",
        "제주도디저트",
        "제주도마카롱",
        "서귀포",
        "제주도수제버거",
        "배달",
        "제주샐러드",
        "국수맛집",
        "개별룸",
        "제주혼술",
        "단체주문",
        "삼겹살",
        "트램폴린카페",
        "공항근처",
        "근고기",
        "할랄푸드",
        "수제맥주전문",
        "해산물",
        "주문제작케이크",
        "전복죽",
        "회포장",
        "가맥",
        "제주동문시장맛집",
        "탐나는전",
        "동문시장맛집",
        "마카롱",
        "칼국수",
        "퓨전한정식",
        "감성주점",
        "제주주문케이크",
        "아라동카페",
        "휘낭시에",
        "서귀포아침식사",
        "쇠소깍맛집",
        "함덕흑돼지",
        "함덕횟집",
        "제주함덕맛집",
        "베이커리",
        "케이크",
        "아늑한",
        "성산술집",
        "섭지코지맛집",
        "우도맛집",
        "제주소품샵",
        "제주편집샵",
        "제주카이막",
        "당근케이크",
        "노트북하기좋은",
        "애월읍카페",
        "수플레",
        "컬쳐카페",
        "애월커피맛집",
        "자전거테마카페",
        "족욕카페",
        "아이스크림",
        "제로웨이스트샵",
        "드립커피전문",
        "요거트카페",
        "크로플",
        "용두암카페",
        "아인슈페너",
        "아메리카노",
        "밀크티",
        "이도이동카페",
        "하도리카페",
        "제주성산카페",
        "제주서핑",
        "목공체험",
        "보트투어",
        "제트스키",
        "제트보트",
        "전기자전거대여",
        "성지순례",
        "로봇만들기체험",
        "로봇박물관",
        "야간개장",
        "유리공예",
        "어린이도서관",
        "오페라공연",
        "실내데이트",
        "체험미술",
        "뮤지컬공연",
        "이색박물관",
        "공연장",
        "아쿠아리움",
        "카트체험장",
        "키즈카페",
        "힐링",
        "유채꽃",
        "노천온천",
        "핑크뮬리카페",
        "제주도관광지",
        "귤따기체험",
        "제주도가볼만한곳",
        "예약제",
        "위스키바",
        "협재해물라면",
        "노을맛집",
        "제주수제버거맛집",
        "해물라면맛집",
        "대정읍맛집",
        "서귀포라멘",
        "선술집",
        "돈마호크",
        "제주도브런치",
        "제주혼밥",
        "비양도",
        "함바식당",
        "금능해수욕장",
        "쌀국수맛집",
        "제주브런치맛집",
        "돌하르방마카롱",
        "이탈리안레스토랑",
        "와인다이닝",
        "제주협재해수욕장",
        "협재흑돼지",
        "제주선물",
        "와인카페",
        "특수부위",
        "제주모슬포맛집",
        "팥빙수",
        "리조또",
        "협재",
        "제주도갈치조림",
        "제주통갈치조림",
        "뼈해장국",
        "해물갈비찜",
        "국밥",
        "순대",
        "한림해장국",
        "돈까스맛집",
        "퓨전포차",
        "1인피자",
        "제주라멘",
        "한우",
        "사계바다",
        "서귀포데이트",
        "서귀포파스타",
        "제주도파스타",
        "백종원의골목식당",
        "제주김밥",
        "제주김밥맛집",
        "제주안덕면맛집",
        "랍스타",
        "물회",
        "밥집",
        "애월읍맛집",
        "애월펍",
        "제주도술집",
        "제주회포장",
        "육회",
        "제주도빵집",
        "빵맛집",
        "제주중문관광단지",
        "애월흑돼지",
        "우동",
        "애월칼국수",
        "애월해안도로맛집",
        "모듬회",
        "제주도피자",
        "수제피자",
        "애월해안도로",
        "제주카레맛집",
        "제주화덕피자",
        "중문술집",
        "중문관광단지",
        "탕수육",
        "브런치뷔페",
        "서귀포베이커리",
        "해물찜",
        "제주와인",
        "제주한식",
        "중문횟집",
        "제주갈치회",
        "제주고기집",
        "중문흑돼지맛집",
        "중문아침식사",
        "서귀포와인바",
        "중화포차",
        "제주시술집",
        "야키토리",
        "소고기",
        "서귀포횟집",
        "워터에이징숙성",
        "이호테우해변맛집",
        "제주공항흑돼지",
        "제주바베큐",
        "저온숙성",
        "이호테우해변",
        "빵지순례",
        "한우오마카세",
        "퓨전분식",
        "신제주카페",
        "제주도도넛",
        "제주냉면",
        "반미",
        "맥주",
        "제주이자카야",
        "노형동",
        "드림타워",
        "갈비찜",
        "고사리갈치조림",
        "와인레스토랑",
        "제주칵테일바",
        "제주혼술바",
        "제주돼지",
        "피자맥주",
        "퓨전요리",
        "용두암맛집",
        "한라수목원",
        "모임하기좋은곳",
        "공항맛집",
        "매운음식맛집",
        "제주레스토랑",
        "방어회",
        "저녁식사",
        "베이글",
        "닭칼국수",
        "월드컵중계",
        "참치무한리필",
        "산낙지",
        "횟집",
        "접짝뼈국",
        "제주공항근처횟집",
        "제주딱새우회",
        "제주시아침식사",
        "동문시장근처",
        "유럽가정식",
        "제주떡집",
        "서귀포떡집",
        "답례떡",
        "약선요리",
        "제주돈까스맛집",
        "제주시고기국수",
        "쌀국수",
        "동태찌개",
        "제주레터링케이크",
        "제주탑동술집",
        "제주파스타맛집",
        "샐러드",
        "제주메밀",
        "서귀포흑돼지맛집",
        "백반",
        "냉동삼겹살",
        "김치찌개",
        "닭볶음탕",
        "제주고사리해장국",
        "제주몸국",
        "제주탑동맛집",
        "동문시장횟집",
        "제주딱새우",
        "새벽술집",
        "제주도돈까스",
        "야외식당",
        "이유식카페",
        "퓨전선술집",
        "퓨전술집",
        "제주베이글",
        "제주시청카페",
        "국민지원금",
        "조개칼국수",
        "단체모임",
        "제주디저트맛집",
        "제주국제공항",
        "제주도해장국",
        "서귀포쌀국수",
        "동홍동맛집",
        "제주도시락",
        "특수부위맛집",
        "이중섭거리맛집",
        "초밥",
        "회",
        "구움과자",
        "까눌레",
        "제주도스쿠버",
        "서귀포해장국",
        "수육",
        "삼양맛집",
        "삼화지구맛집",
        "함덕파스타",
        "조천수제버거",
        "제주갈치맛집",
        "쇠소깍카페",
        "함덕",
        "함덕해변맛집",
        "사려니숲길",
        "함덕아침식사",
        "밀면",
        "퓨전이탈리안",
        "크림치즈",
        "제주도신상카페",
        "피크닉세트대여",
        "제주구좌읍맛집",
        "제주월정리맛집",
        "성읍민속마을맛집",
        "월정리해변",
        "행원리맛집",
        "해비치맛집",
        "서귀포수제버거",
        "세화해수욕장",
        "세화해변",
        "초콜릿카페",
        "제주시브런치",
        "하도리맛집",
        "제주성산흑돼지",
        "종달리맛집",
        "성산흑돼지",
        "반려동물동반카페",
        "제주협재카페",
        "협재브런치",
        "귤체험",
        "제주감귤체험",
        "제주한림카페",
        "제주크로플",
        "제주수플레",
        "대정카페",
        "모슬포카페",
        "로스팅",
        "제주쿠키",
        "다쿠아즈",
        "아담한",
        "곽지카페",
        "비건디저트",
        "애월브런치카페",
        "애월해안도로카페",
        "공간대여",
        "로봇카페",
        "애월소품샵",
        "소품샵",
        "애월빵집",
        "제주도애월카페",
        "해안도로카페",
        "제주중문카페",
        "인생샷",
        "브라우니",
        "티클래스",
        "티하우스",
        "파충류카페",
        "정원카페",
        "망고디져트점",
        "제주애플망고",
        "태국망고",
        "필리핀망고",
        "제주떡카페",
        "수제청",
        "마들렌",
        "이색데이트",
        "24시간카페",
        "연동카페",
        "서귀포티하우스",
        "제주도티하우스",
        "크림커피",
        "뷰티카페",
        "조용한카페",
        "제주핸드드립",
        "짜이",
        "다락방카페",
        "바닐라라떼",
        "루프탑카페",
        "스페셜티커피",
        "제주커피",
        "제주휘낭시에",
        "제주로스터리카페",
        "한식디저트카페",
        "제주에스프레소바",
        "와플카페",
        "베라체카페",
        "프렌치토스트",
        "슬라임카페",
        "한라산뷰",
        "제주삼양카페",
        "고양이소품샵",
        "남원읍카페",
        "서귀포남원카페",
        "제주애견카페",
        "제주뷰카페",
        "조천카페",
        "애견운동장",
        "제주애견동반",
        "제주당근주스",
        "월정리해수욕장",
        "평대카페",
        "우도카페",
        "요트투어",
        "제주도요트",
        "제주원데이클래스",
        "페러세일링",
        "이색체험",
        "제주도액티비티",
        "스쿠버다이빙체험",
        "캔들클래스",
        "다이빙체험",
        "스킨스쿠버",
        "제주도자전거대여",
        "자전거대여",
        "제주공방",
        "골프텔",
        "입욕제공방",
        "패러글라이딩",
        "역사문화관",
        "서예체험",
        "제주도공연",
        "제주코끼리",
        "코끼리",
        "코끼리쇼",
        "코끼리트레킹",
        "코끼리테마쇼",
        "공예체험",
        "전통공예체험",
        "왁스뮤지엄",
        "카트체험",
        "어린이전시",
        "자연체험",
        "직업체험",
        "어린이교육프로그램",
        "컴퓨터박물관",
        "아이스뮤지엄",
        "갤러리",
        "아트페어",
        "화랑",
        "미술작품",
        "클래식공연",
        "북콘서트",
        "인형극",
        "전망대",
        "민속놀이체험",
        "문화유물전시관",
        "입체영상관",
        "현장체험학습",
        "어린이박물관",
        "그림전시",
        "예술적인분위기",
        "orchid",
        "돈내코",
        "자생지",
        "전시관",
        "한란",
        "야외공연장",
        "역사박물관",
        "문화공연",
        "곤충파충류체험전",
        "실내클라이밍",
        "클립앤클라임",
        "실내암벽",
        "팜파스그라스",
        "탈출체험",
        "갈대밭",
        "고카트",
        "실내수영장",
        "돌고래쇼",
        "홍가시나무",
        "상고대",
        "레고박물관",
        "제주놀이터",
        "제주실내놀이터",
        "제주키즈카페",
        "제주키즈파크",
        "차롱치유밥상",
        "100대명산",
        "제주도카트",
        "제주도카트장",
        "제주액티비티",
        "제주카트",
        "제주카트레이싱",
        "버기카",
        "서바이벌체험",
        "짚라인",
        "생태공원",
        "캠핑장",
        "코스모스",
        "농장체험",
        "생태체험",
        "모노레일",
        "제주도관광",
        "제주도실내관광지",
        "제주도테마파크",
        "제주동부관광",
        "데이트추천",
        "친환경귤농장",
        "친환경귤따기",
        "반려동물",
        "자연",
        "투명카약",
        "족욕체험",
        "일몰감상",
        "우도여행",
        "훈데르트바서파크",
        "보리굴비",
        "연잎밥",
        "한정식",
        "혼자여행",
        "신창해물라면",
        "한경면",
        "제주한경면맛집",
        "캠핑",
        "야외",
        "돈가스",
        "제주로컬푸드전문",
        "판포포구",
        "판포맛집",
        "제주도해물라면",
        "짚불구이",
        "국제영어도시맛집",
        "네이버온라인예약",
        "당일예약전화문의",
        "사전예약제",
        "온라인예약",
        "스테이크맛집",
        "한우스테이크",
        "제주빵투어",
        "제주와인샵",
        "제주순살갈치",
        "협재갈치조림",
        "협재고기국수",
        "협재국밥",
        "협재해장",
        "금능",
        "제주서쪽",
        "제주금능맛집",
        "제주영어마을맛집",
        "제주tv나온맛집",
        "비양도맛집",
        "보말손칼국수",
        "뿔소라회",
        "산양큰엉곶",
        "산양큰엉곶근처",
        "산양큰엉곶주변",
        "제주코스요리",
        "덮밥",
        "금능혼술",
        "제주금능술집",
        "제주협재술집",
        "자연산제철생선회",
        "제주금능덮밥",
        "협재점심",
        "금능해수욕장맛집",
        "대정맛집",
        "전복맛집",
        "전복음식",
        "오설록맛집",
        "제주서쪽여행코스",
        "제주선물추천",
        "예약필수",
        "크래프트비어",
        "금능협재회배달",
        "협재술집밥집",
        "협재해수욕장횟집",
        "협재회맛집",
        "협재회포장",
        "오분작뚝배기",
        "한림공원맛집",
        "제주위스키바",
        "협재와인바",
        "제주칼국수맛집",
        "협재흑돼지맛집",
        "금능흑돼지",
        "협재포장",
        "제주수제어묵",
        "제주특산물어묵",
        "전복김밥",
        "한림흑돼지",
        "대정읍술집",
        "사케",
        "수제버거맛집",
        "수제무스케잌",
        "수제생초코렛",
        "수제쨈",
        "수제타르트",
        "모슬포항근처맛집",
        "물회맛집",
        "보말칼국수맛집",
        "전복죽맛집",
        "제주송악산맛집",
        "신화역사공원맛집",
        "오설록",
        "라자냐",
        "협재게스트하우스",
        "제주도아침식사",
        "감성인테리어",
        "깨끗한",
        "음식이맛있는",
        "제주도케이크맛집",
        "제주도주문케이크",
        "청수리케이크",
        "한경면케이크",
        "이색김밥",
        "제주한림흑돼지",
        "제주양념갈비",
        "감자탕",
        "묵은지",
        "뼈찜",
        "제주아구찜",
        "제주한림해물찜",
        "제주해물찜",
        "한림아구찜",
        "한림해물찜",
        "고급스러운",
        "솥밥",
        "한림",
        "한식코스요리",
        "향토음식",
        "수제식혜",
        "제주도해물갈비찜",
        "한림읍맛집",
        "족발",
        "근처식당",
        "식당",
        "한림밥집",
        "금능피자",
        "한림피자",
        "한림피자맛집",
        "협재피자",
        "협재피자맛집",
        "감자탕전문점",
        "제주산등뼈",
        "근처고기국수",
        "한림고기국수",
        "한림국수집",
        "한림돔배고기",
        "한림순두부",
        "한림해장국맛집",
        "제주국밥",
        "제주서부맛집",
        "제주시횟집",
        "복어지리",
        "아구조림",
        "뼈등심돈까스",
        "제주갈치",
        "대정읍흑돼지",
        "영어교육도시",
        "오셜록티뮤지엄",
        "구억리흑돼지",
        "스토브온",
        "한림보말죽",
        "한림보말칼국수",
        "제주쌈정식",
        "한림정식",
        "고등어쌈밥",
        "제주쌈밥",
        "흑돼지쌈밥",
        "한림점심식사",
        "텐동맛집",
        "화로오마카세",
        "신례명주위스키",
        "애월lp바",
        "애월한림협재혼술",
        "제주lp바",
        "제주하이볼",
        "송악산바다뷰피자",
        "사계피자맛집",
        "형제섬뷰피자맛집",
        "마라도선착장맛집",
        "올레10길맛집",
        "사계리카페",
        "쇼콜라티에",
        "초콜릿체험",
        "생면파스타",
        "탄탄면",
        "백종원골목식당",
        "한림파스타",
        "협재파스타",
        "꿀봉",
        "돼지강정",
        "금오름카페",
        "제주빵맛집",
        "한림베이커리",
        "냉면랩소디",
        "귀덕향사",
        "수제햄버거",
        "한림버거",
        "김밥맛집",
        "채식김밥맛집",
        "통해물갈치조림",
        "고등어회전문",
        "산방산횟집",
        "용머리횟집",
        "제주신화월드",
        "제주사계해변",
        "제주송악산",
        "고기",
        "산방산탄산온천",
        "사계리와인바",
        "아시아음식",
        "burger",
        "버거",
        "곽지해수욕장술집",
        "곽지혼술",
        "애월이자카야",
        "애월혼술",
        "곽지해수욕장",
        "스페니쉬풍",
        "곽지맛집",
        "곽지밥집",
        "제주한상차림",
        "제주혼밥맛집",
        "애월노을식당",
        "애월바다뷰식당",
        "애월애견동반식당",
        "애월퀸동상",
        "하갈비",
        "제주도버거",
        "제주도애월",
        "송리단길",
        "송리단길파스타",
        "잠실데이트",
        "잠실파스타",
        "연돈",
        "제주도돈가스",
        "산방산해물라면",
        "용머라해안맛집",
        "반려견동반식당",
        "스포츠펍",
        "시푸드뷔페",
        "점심뷔페",
        "도민찐맛집",
        "매운갈비찜",
        "봉성리맛집",
        "애월갈비찜",
        "애월갈치구이",
        "제주한담해변맛집",
        "곽지해수욕장맛집",
        "애월바",
        "애월분위기좋은곳",
        "애월브런치",
        "제주애월브런치",
        "제주애월항맛집",
        "제주애월횟집",
        "제주애월밥집",
        "제주오마카세",
        "제주초밥",
        "육전",
        "육회비빔밥",
        "빵투어",
        "호도",
        "캐주얼일식",
        "터키요리",
        "인도음식",
        "애월밥집",
        "애월소곱창",
        "애월혼밥",
        "제주소곱창",
        "반려동물동반",
        "새우튀김",
        "야끼소바",
        "항아리바베큐",
        "독일가정식",
        "더럭초인근맛집",
        "애월도민맛집",
        "애월파스타맛집",
        "전용주차장",
        "제주도핫플",
        "하가리맛집",
        "하가리밀면",
        "애월면사무소",
        "애월해안도로밥집",
        "제주도칼국수",
        "제주면사무소",
        "객주리조림",
        "쥐치조림",
        "제주대평리",
        "성게비빔밥",
        "유기농",
        "애월수제버거",
        "애월햄버거",
        "애월파스타",
        "기업행사",
        "스몰웨딩",
        "프라이빗룸",
        "소길리",
        "중식뷔페",
        "애월해물라면",
        "제주노라바",
        "981파크",
        "송훈랜드",
        "아르떼뮤지엄",
        "토종흑돼지",
        "송훈쉐프레스토랑",
        "송훈파크",
        "제주피자맛집",
        "중문와인",
        "중문이자카야",
        "제주일상",
        "고사리해장국",
        "서귀포생선구이",
        "제주중문아침식사",
        "중문생선구이",
        "마트료시카",
        "마트료시카만들기",
        "한담해변",
        "각종단체모임",
        "제주생식빵",
        "중문빵집",
        "제주베이커리",
        "흑돼지등심탕수육",
        "유니짜장",
        "애월짬뽕",
        "유수암중식당",
        "현지인식당",
        "유수암리맛집",
        "애월횟집",
        "제주도통갈치맛집",
        "제주도해물탕맛집",
        "제주애월회맛집",
        "베트남쌀국수",
        "애월쌀국수",
        "제주베트남쌀국수",
        "간장게장",
        "아귀찜",
        "해물모듬장",
        "애월정육식당",
        "애월회센터",
        "3인이하",
        "으른술집",
        "증류주만있어요",
        "데이트",
        "중문브런치",
        "제주대관",
        "제주파티룸",
        "제주행사",
        "중문갈치조림맛집",
        "제주중문흑돼지",
        "주차가능",
        "주차장",
        "중문도민맛집",
        "중문순두부맛집",
        "제주도중문횟집",
        "중문고등어회",
        "서귀포갈치",
        "제주도갈치",
        "제주통갈치",
        "흑돼지두루치기",
        "서귀포돼지고기",
        "제주도돈마호크",
        "서귀포정이가네",
        "정이가네",
        "중문해장국",
        "중문와인바",
        "문동일셰프",
        "떡갈비칼국수",
        "문동일셰프녹차고",
        "육개장과전복찜",
        "애월추천",
        "애월타코",
        "단체",
        "제주산한우",
        "제주라면",
        "즉석떡볶이",
        "중문아침",
        "술국",
        "중문해장",
        "기네스생",
        "서귀포펍",
        "중문펍",
        "어멍똘보말칼국수",
        "제주로컬맛집",
        "중문보말칼국맛집",
        "서귀포갈비",
        "중문소고기",
        "매운문어갈비찜",
        "제주도매운갈비찜",
        "냉모밀",
        "스키야키",
        "제주갈치구이맛집",
        "통갈치구이",
        "햄버거",
        "중문바다뷰횟집",
        "야외맛집",
        "제주도중문맛집",
        "숙성근고기",
        "생갈비",
        "중문갈치구이",
        "제주도두봉맛집",
        "제주외도동맛집",
        "누룽지통닭",
        "외도맛집",
        "전기구이",
        "제주숲",
        "호프",
        "고깃집",
        "돼지꼬리",
        "숯불구이",
        "제주선물용",
        "피칸파이",
        "선물용디저트",
        "Jeju3527",
        "Jeju352",
        "pasta",
        "pizza",
        "도두항",
        "제주시해물",
        "올레길",
        "올레길7코스",
        "제주빵지순례",
        "제주도혼술",
        "제주시와인바",
        "제주데이트",
        "도두항맛집",
        "도두항횟집",
        "이호태우해변맛집",
        "오뎅바",
        "채식뷔페",
        "노형동김밥",
        "노형동떡볶이",
        "노형동분식",
        "노형동쫄면",
        "제주도넛",
        "등심",
        "제주소고기",
        "한우육사시미",
        "한우전문점",
        "안심",
        "제주냉면맛집",
        "바게트",
        "노형쌀국수",
        "떡볶이맛집",
        "볶음밥맛집",
        "낙지연포탕맛집",
        "노형동술집",
        "무늬오징어맛집",
        "제주노형동",
        "오란다짱좋아",
        "오무라이스",
        "유아의자",
        "김치볶음밥",
        "노형샐러드맛집",
        "제주샐러드맛집",
        "노형도시락",
        "노형샌드위치",
        "노형동흑돼지맛집",
        "유아의자없음",
        "제주롤맛집",
        "제주연어맛집",
        "제주우동맛집",
        "제주타마고산도",
        "대만가정식",
        "유럽풍분위기",
        "제주시레스토랑",
        "제주시스테이크",
        "제주분위기맛집",
        "노형맛집",
        "양꼬치",
        "신제주이마트",
        "고기비빔국수",
        "순대국밥",
        "제주노형맛집",
        "도두고기집",
        "제주흑돼지전문점",
        "서귀포시맛집",
        "제주일식",
        "제주장어",
        "제주장어덮밥",
        "수목원길야시장",
        "제주한라수목원",
        "부산어묵",
        "쌀떡볶이",
        "연동분식맛집",
        "제주도분식맛집",
        "수목원맛집",
        "돈차돌",
        "막창",
        "생오겹살",
        "한우차돌",
        "비스트로바",
        "제주감자탕",
        "제주하얏트맛집",
        "그랜드하얏트맛집",
        "드림타워맛집",
        "메종글래드맛집",
        "양꼬치무한리필",
        "제주소수의견",
        "제주돈마호크",
        "제즈도끼삼겹살",
        "노형흑돼지맛집",
        "두루치기맛집",
        "드림타워근처맛집",
        "흑돼지돌판구이",
        "스시오마카세",
        "제주스시오마카",
        "연동",
        "돈가스맛집",
        "마켓프레쉬",
        "제주돈가스",
        "피자펍",
        "마늘치킨",
        "신제주치킨",
        "제주치킨",
        "크림치킨",
        "제주마늘치킨",
        "제주도민",
        "랍스터",
        "소랑호젠인제주",
        "제주공항주변맛집",
        "강정동맛집",
        "제주도베이커리",
        "1인식사",
        "모임하기좋은식당",
        "혼밥식당",
        "숙성고기",
        "등심돈까스",
        "제주돈까스",
        "치즈돈까스",
        "중식당",
        "중화요리주점",
        "중국집",
        "짜장면",
        "짬뽕",
        "제주대게",
        "제주킹크랩",
        "데이트맛집",
        "숙성회",
        "곱창맛집",
        "묵은지고등어림",
        "전복돼지갈비찜",
        "제주향토음식",
        "수제막걸리",
        "팔당닭발",
        "팔당오징어",
        "제주분위기술집",
        "제주수육",
        "제주연동술집",
        "제주제원술집",
        "제주한식맛집",
        "제주마라탕",
        "제주신상맛집",
        "제주덮밥맛집",
        "연동고기집",
        "제주시흑돼지맛집",
        "흑미면옥",
        "공항근처고기국수",
        "해장고기국수",
        "삼치회",
        "자연산회",
        "꼬치구이",
        "연동술집",
        "치맥",
        "올레국수",
        "제주올래국수",
        "제주장칼국수",
        "돼지불백",
        "생고기김치찌개",
        "얼큰칼국수",
        "핸드드립커피",
        "수제건강빵",
        "1인정식",
        "제주돼지수육",
        "철판볶음요리",
        "대게무한리필",
        "홍게무한리필",
        "제주생선구이",
        "캐주얼와인바",
        "이탈리안",
        "돌광어",
        "한치",
        "맛있는집",
        "신시가지맛집",
        "혼밥맛집",
        "가성비깡패",
        "맛있는술안주",
        "와인마시기좋은",
        "한라토닉",
        "메밀간장기름국수",
        "제주고등어회",
        "제주고기국수맛집",
        "용담맛집",
        "제주용담맛집",
        "제주용담해안도로",
        "제주용두암맛집",
        "제주용담흑돼지",
        "모임하기좋은맛집",
        "오션뷰술집",
        "참치",
        "제주도빵지순례",
        "서귀포시",
        "한우숯불구이",
        "현지맛집",
        "흑돼지오겹살",
        "떡집",
        "이비지떡",
        "단체모임예약",
        "서귀포뷰맛집",
        "서귀포한식",
        "공항근처돈까스",
        "구제주돈까스",
        "제주공항고기국수",
        "제주공항아침식사",
        "시외버스터미널",
        "제주비건샌드위치",
        "제주비건식당",
        "제주샌드위치",
        "껌승",
        "레드사이공",
        "분띳능",
        "수제사탕",
        "도너츠",
        "제주크림도너츠",
        "제주크림도넛",
        "크림도넛",
        "기념떡",
        "제주공항국수",
        "고등어소바",
        "사케동",
        "우니소바",
        "산도위치",
        "제주산도위치",
        "제주도샐러드",
        "제주도스프",
        "제주캠핑",
        "제주도분식",
        "제주소바",
        "청귤소바",
        "돈사촌",
        "인기맛집",
        "전복요리",
        "제주도흑돼지맛집",
        "지라시",
        "치라시",
        "카이센",
        "서귀포현지인맛집",
        "제주도짜글이",
        "제주도현지인맛집",
        "짜글이맛집",
        "흑돼지짜글이맛집",
        "제주시갈치조림",
        "호텔맛집",
        "매운탕",
        "우럭회",
        "JACKSON",
        "잭슨피자",
        "합동청사점",
        "무항생재암퇘지",
        "전복장",
        "야간술집",
        "탕탕이",
        "이자카야펍",
        "제주도고기집",
        "제주도삼겹살",
        "제주새우버터구이",
        "제주생새우오도리",
        "제주연포탕",
        "제주조개구이",
        "제주해물탕",
        "자갈구이",
        "감바스",
        "제주다트",
        "제주웨스턴바",
        "제주펍",
        "올리다버거",
        "제주선물가게",
        "제주초콜릿",
        "초콜릿전문점",
        "초콜릿",
        "꼬들대패",
        "대패삼겹살",
        "볶음밥",
        "옛날삼겹살",
        "두루치기",
        "뒷고기",
        "제주고사리육개장",
        "제주시청고기맛집",
        "제주시청근처맛집",
        "제주시청흑돼지",
        "제주공항흑돼지집",
        "제주칵테일",
        "혼술바",
        "제주혼술집",
        "양조장",
        "제주내추럴와인",
        "탑동술집",
        "탑동와인바",
        "관덕정",
        "도시락",
        "동문시장",
        "다이닝바",
        "수입맥주",
        "와인펍",
        "칵테일불쇼",
        "제주기회횟집",
        "제주공항횟집",
        "예멘음식",
        "케밥",
        "팔라펠",
        "할랄",
        "허머스",
        "제주동문시장횟집",
        "제주생대패오겹살",
        "제주흑돼지거리",
        "휘슬락맛집",
        "제주돈가스맛집",
        "닭강정",
        "제주닭강정",
        "탐라온닭강정",
        "빵집",
        "흑돼지돈카츠",
        "사라봉맛집",
        "스몰비어",
        "noodle",
        "보말",
        "제주뷔페",
        "제주상견례",
        "제주아라동맛집",
        "대만음식",
        "우육면",
        "제주우육면",
        "제주이도동맛집",
        "웰빙",
        "단체회식하기좋은",
        "숙성돼지고기",
        "제주수제디저트",
        "제주도라운지",
        "제주라운지바",
        "제주클럽",
        "제주시청돈까스",
        "제주시청떡볶이",
        "제주시청분식",
        "고등어조림",
        "돌솥밥",
        "바",
        "제주시청",
        "잔술",
        "제주치즈돈까스집",
        "제주하이볼맛집",
        "재난지원금",
        "연탄구이",
        "시장통닭",
        "제주도치킨맛집",
        "제주도치킨",
        "제주시장통닭",
        "간장게장맛집",
        "구남동맛집",
        "새우장맛집",
        "추어탕맛집",
        "제주칼국수",
        "이도이동맛집",
        "제주고기맛집",
        "제주법원맛집",
        "제주숙성돼지",
        "도가니탕",
        "찹쌀순대",
        "제주시청술집",
        "제주요리주점",
        "제주주도",
        "제주한식주점",
        "돈카츠카레",
        "수제카레",
        "안심카츠정식",
        "제주국수마당",
        "가정식",
        "일도이동건강식",
        "일도이동보양식",
        "제주도건강식",
        "제주도보양식",
        "추어탕",
        "한정식뷔페",
        "당일구매케이크",
        "찌개",
        "서귀포백숙",
        "서귀포점심",
        "서귀포점심맛집",
        "서귀포점심추천",
        "아라동디저트",
        "제주도파이",
        "제주소고기맛집",
        "제주시청소고기",
        "제주아라동한우",
        "제주육사시미",
        "샌드위치맛집",
        "샐러드맛집",
        "제주사시미",
        "제주사케바",
        "제주심야식당",
        "아라동한식뷔페",
        "보쌈",
        "베라체맛집",
        "이도동맛집",
        "제주놀이방식당",
        "제주함박스테이크",
        "라멘",
        "라멘야누",
        "제주비건카페",
        "호주식브런치",
        "호주브런치",
        "밀랍에이징",
        "자연산생선",
        "제주시해장국",
        "제주항근처맛집",
        "제주시내밥집",
        "제주전복돌솥밥",
        "제주황게장",
        "고기집",
        "돼지고기김치찌개",
        "100%예약제",
        "제주도참치",
        "제주시참치",
        "제주참치",
        "애월김밥맛집",
        "제주애월김밥",
        "흑돼지김밥",
        "새연교",
        "서귀포돈까스",
        "외돌개맛집",
        "천지연맛집",
        "황우지해안맛집",
        "서귀pho",
        "제주도똠양꿍",
        "제주도분짜",
        "갈비탕",
        "찜닭",
        "서귀포저녁식사",
        "제주구움과자",
        "편의점포차",
        "서귀포스테이크",
        "제주스테이크",
        "서귀포시내맛집",
        "서홍동맛집",
        "제주뷔페식당",
        "한식부페",
        "제주맛집뷔페",
        "금빌레식당",
        "장사의신",
        "오리백숙",
        "오리탕",
        "단체도시락",
        "유부초밥",
        "서귀포와인핫플",
        "와인소믈리에",
        "와인콜키지프리",
        "흑돼지양념갈비",
        "서귀포떡볶이",
        "제주도떡볶이",
        "올레시장술집",
        "Harbor39",
        "천지연",
        "서귀포도민맛집",
        "서귀포돈가스",
        "포가츠",
        "포카츠",
        "정방폭포근처",
        "천지연폭포근처",
        "딱새우찜",
        "딱새우해물라면",
        "멜튀김",
        "옥돔정식",
        "흑돼지김치찌개",
        "스시",
        "서귀포타코",
        "올레시장먹거리",
        "올레시장야시장",
        "올래시장",
        "쿠키",
        "제주도서귀포맛집",
        "제주도해물뚝배기",
        "서귀포포차",
        "올레시장근처맛집",
        "서귀포갈치구이",
        "서귀포단체식당",
        "서귀포해물뚝배기",
        "모범식당",
        "제주서귀포흑돼지",
        "천지연폭포맛집",
        "서귀포고기국수",
        "올레시장",
        "이중섭거리",
        "정방폭포",
        "흑돼지근고기",
        "전골",
        "해물",
        "해물전골",
        "서귀포고기집",
        "서귀포소고기",
        "서귀포시청맛집",
        "올레시장흑돼지",
        "제주맛집추천",
        "일본라멘",
        "돈코츠라멘",
        "마제멘",
        "미풍해장국",
        "서귀포도시락",
        "연어초밥",
        "서귀포회포장",
        "LA갈비",
        "도민로컬맛집",
        "흑돼지덜미살",
        "흑돼지직화구이",
        "게우비빔밥",
        "부촌전복물회",
        "부촌전복칼국수",
        "텐동",
        "텐동아우라",
        "밀냉면",
        "산방식당",
        "화북맛집",
        "샤브샤브무한리필",
        "서귀포야끼토리",
        "서귀포혼술",
        "서귀포올레시장",
        "매운맛집",
        "제주맘카페서핫한",
        "찐제주도민맛집",
        "비빔칼국수",
        "해물파전",
        "멸치국수",
        "함덕스테이크",
        "마이마이버거",
        "고기뷔페",
        "샐러드정기배송",
        "제주단체샐러드",
        "제주샐러드도시락",
        "제주샐러드배달",
        "브라이덜샤워",
        "가성비넘버원",
        "서귀포베케근처",
        "서귀포식빵집",
        "서귀포제과빵빵",
        "효돈빵집",
        "서귀포몸국",
        "쇠소깍",
        "아강발찜",
        "알동네국수",
        "서귀포브런치카페",
        "쇠소깍술집",
        "제주도브런치카페",
        "보말국",
        "한치물회",
        "함덕수제버거",
        "조천흑돼지",
        "흑돼지연탄구이",
        "몸국맛집",
        "제주도몸국",
        "조천몸국",
        "수와래베이커리",
        "수와래빵집",
        "위미빵집",
        "삼계탕",
        "쌈밥",
        "정식",
        "포장",
        "위미동백군락지",
        "위미항",
        "크래프트맥주",
        "함덕와인",
        "함덕펍",
        "뉴트로",
        "함덕해수욕장술집",
        "타코",
        "치킨",
        "조천술집",
        "함덕식당",
        "함덕혼술",
        "조천읍횟집",
        "훈남횟집",
        "위미맛집",
        "오션뷰식당",
        "위미밥집",
        "위미카레",
        "위미파스타",
        "교래리",
        "닭샤브샤브",
        "도리골토종닭",
        "삼다수숲길",
        "묵은지오겹살찜",
        "에코랜드맛집",
        "에코랜드",
        "전복뚝배기",
        "함덕밥집",
        "함덕저녁식사",
        "함덕점심식사",
        "제주조천맛집",
        "제주함덕흑돼지",
        "제주도한식",
        "함덕백반",
        "함덕포장",
        "소노벨제주맛집",
        "제주공연",
        "제주실내데이트",
        "제주소노벨맛집",
        "함덕근고기",
        "웨스턴스타일",
        "사려니숲길맛집",
        "제주남원읍맛집",
        "샤브샤브맛집",
        "전골맛집",
        "칼국수맛집",
        "동백동산맛집",
        "동백동산카페",
        "선흘리카페",
        "조천읍맛집",
        "남원",
        "분식",
        "서귀포남원돈카츠",
        "서귀포남원맛집",
        "서귀포치즈돈카츠",
        "제주수제돈까스",
        "바베큐뷔페",
        "스프",
        "독일식요리",
        "김녕술집",
        "김녕식당",
        "김녕해변맛집",
        "김녕해수욕장맛집",
        "까망도그",
        "문어핫도그",
        "성세기해변맛집",
        "바다낚시",
        "가시리",
        "부페",
        "점심맛집",
        "표선",
        "향촌",
        "제주도갈치구이",
        "제주표선갈치맛집",
        "음식점",
        "제주동쪽",
        "1인실",
        "2인실",
        "더덕비빔밥",
        "비건맛집",
        "피자맛집",
        "배달의민족포장",
        "송당맛집",
        "제주닭볶음탕",
        "제주닭도리탕",
        "기념일선물",
        "답례품",
        "생일선물",
        "여행선물",
        "제주동부맛집",
        "제주해물라면맛집",
        "월정리브런치",
        "월정리빵집",
        "소노캄맛집",
        "표선흑돼지",
        "성읍맛집",
        "흑돼지오겹맛집",
        "고사리맛집",
        "고사리오겹살",
        "고사리주물럭",
        "표선성읍맛집",
        "갈치솥밥",
        "구좌읍",
        "전복돌솥밥",
        "전복솥밥",
        "제주피쉬앤칩스",
        "밭담",
        "구좌읍초밥",
        "코난비치맛집",
        "구좌읍비건",
        "비건브런치",
        "구좌읍흑돼지",
        "구좌흑돼지",
        "김녕흑돼지",
        "월정리흑돼지",
        "야식배달",
        "타코맛집",
        "표선타코",
        "순두부찌게",
        "해비치해수욕장",
        "해비치호텔",
        "표선와인",
        "구좌읍해안도로",
        "김녕해수욕장",
        "표선해수욕장",
        "한라산아래첫마을",
        "해비치근처맛집",
        "서귀포햄버거",
        "제주도햄버거",
        "표선접짝뼈국",
        "표선아침식사",
        "제주연미정",
        "제주전복밥",
        "비자림맛집",
        "세화리맛집",
        "제주구좌맛집",
        "세화쌀국수",
        "제주도쌀국수",
        "제주도태국음식",
        "수제초콜릿전문",
        "카카오전문점",
        "온평포구맛집",
        "세화술집",
        "제주세화맛집",
        "성산정육식당",
        "성산한우",
        "표선정육식당",
        "표선한우",
        "당근스프",
        "수제브런치",
        "하도리브런치",
        "세화파스타",
        "하도리파스타",
        "제주파스타추천",
        "서귀포돌문어",
        "성산돌문어",
        "우동맛집",
        "제주전통주바",
        "문어라면",
        "프랑스가정식",
        "제주LP바",
        "제주뮤직바",
        "비빔밥",
        "쭈꾸미",
        "채식식당",
        "해물전",
        "제주회",
        "회덮밥",
        "다이닝",
        "딱새우회찜",
        "그대와함께라면",
        "흑돼지돈가스",
        "섭지코지흑돼지",
        "성산일출봉흑돼지",
        "돼지고기구이",
        "직접뽑는냉면",
        "성산흑돼지맛집",
        "성산",
        "근고기맛집",
        "대파국수",
        "성산흑돼지근고기",
        "열정돈흑돼지",
        "흑돼지고깃집",
        "수제찐빵",
        "제주성산찐빵",
        "제주찐빵",
        "제주하마보",
        "치즈찐빵",
        "장어덮밥",
        "히츠마부시",
        "해물칼국수",
        "조개구이",
        "제주섭지코지",
        "이어돈성산",
        "제주이어돈",
        "데이트장소",
        "성산일출봉횟집",
        "4인까지식사가능",
        "4시이후포장만",
        "대기1시간",
        "포장전화주문가능",
        "영국식당",
        "고성리술집",
        "성산읍술집",
        "문어해물칼국수",
        "보말전복죽",
        "보말전복칼국수",
        "한치해물전",
        "아침식사되는곳",
        "안주가맛있는",
        "혼술하기좋은",
        "#갈치조림1인분",
        "#생물통갈치구이",
        "#오분작뚝배기",
        "#제주은갈치조림",
        "#혼밥가능",
        "성산갈치구이",
        "성산갈치조림",
        "제주성산갈치",
        "성산돈까스맛집",
        "우도주민맛집",
        "우도중국집",
        "우도짜장면",
        "우도짬뽕맛집",
        "우도전복물회",
        "전복전문점",
        "제주우도맛집",
        "제주향토음식점",
        "노을명소",
        "신창해안도로",
        "수월봉카페",
        "차귀도카페",
        "제주옷가게",
        "제주카페스타그램",
        "제주키즈존카페",
        "판포리카페",
        "제주금능카페",
        "녹차카페",
        "말차카페",
        "산노루",
        "산노루삼성",
        "제주산노루",
        "서귀포애견동반",
        "서귀포카이막",
        "정원",
        "프라이빗",
        "분위기좋은카페",
        "반련견동반카페",
        "제주한경면카페",
        "협재핸드드립",
        "협재베이커리",
        "가드닝카페",
        "금능카페",
        "영어도시카페",
        "오설록카페",
        "신화월드카페",
        "산양곶자왈카페",
        "문구",
        "차",
        "편지",
        "영어교육도시카페",
        "수제치즈",
        "협재베이글",
        "에스프레소",
        "오우야모슬포",
        "오우야제주",
        "대정읍카페",
        "모슬포커피",
        "프릳츠",
        "커피리브레",
        "베이커리까페",
        "협재빵집",
        "원두판매",
        "한림베이커리카페",
        "협재베이커리카페",
        "협재에그타르트",
        "로컬카페",
        "저지예술인마을",
        "제주드로잉카페",
        "제주체험",
        "폐교카페",
        "비양놀",
        "제주바다뷰카페",
        "제주에이드",
        "제주포토존카페",
        "테이아웃전문",
        "로스팅카페",
        "선물포장",
        "한림카페추천",
        "이색적인",
        "무운",
        "산방산카페",
        "동물먹이체험",
        "제주동물원",
        "펫프랜들리",
        "키즈프랜들리",
        "7밀리그램",
        "잭다니엘",
        "잭콕",
        "이중섭미술관",
        "귀덕맛집",
        "귀덕술집",
        "카츠산도",
        "한림술집",
        "유럽빵",
        "산방산브런치",
        "수제발효빵",
        "제주핫플카페",
        "애월빵공장천안",
        "제주라운지펍",
        "다이닝카페",
        "애월카페거리",
        "마운틴뷰카페",
        "애월마카롱",
        "제주마카롱맛집",
        "협재마카롱",
        "애월감성카페",
        "글루텐프리디저트",
        "비건케이크",
        "서귀포핫플",
        "금오름맛집",
        "이시돌맛집",
        "제주갈레트",
        "밀크티맛집",
        "슈프림카페",
        "보태니컬아트",
        "홀케이크예약",
        "제주사이폰커피",
        "제주타르트",
        "디카페인커피",
        "뱅쇼",
        "요거트보울",
        "팝업스토어",
        "창고형카페",
        "애월애견동반카페",
        "애월추천카페",
        "애월핫플",
        "고내리카페",
        "더바당",
        "재즈카페",
        "애월뷰맛집",
        "모래놀이터",
        "슬라임체험",
        "아트카페",
        "도시락카페",
        "애월와인가게",
        "커피와인체험",
        "크리스마스카페",
        "회전목마",
        "소길리카페",
        "상가리야자숲",
        "효리네민박",
        "제주도이색카페",
        "통창카페",
        "구엄카페",
        "서쪽카페",
        "논짓물족욕카페",
        "제주족욕카페",
        "안마의자카페",
        "네츄럴와인",
        "인스타",
        "다도카페",
        "테린느",
        "에스프레소커피바",
        "중문색달해수욕장",
        "홀츠애월",
        "애월디저트",
        "귤밭카페",
        "스콘맛집",
        "보이차",
        "찻집",
        "티코스",
        "서귀포디저트",
        "서귀포케이크",
        "주문케이크",
        "하귀카페",
        "오르덴",
        "카페오르덴",
        "외도동카페",
        "생딸기라떼",
        "제주라운지",
        "중문라운지",
        "쿠키맛집",
        "제주떡까페",
        "중문떡집",
        "제주스러움",
        "크로플맛집",
        "스테이위드커피",
        "커피정기구독",
        "보드게임대여",
        "와플",
        "스페셜티카페",
        "치즈케이크",
        "다원쿠키",
        "스모어쿠키",
        "디저트답례품",
        "제주노형브런치",
        "제주감성카페추천",
        "제주빈티지카페",
        "제주공간대여",
        "제주도대관",
        "제주도샌드위치",
        "녹차빙수",
        "망고빙수",
        "제주도빙수맛집",
        "단팥죽",
        "드레스카페",
        "수목원카페",
        "노형카페",
        "제주디져트카페",
        "용담해안도로카페",
        "무지개해안도로",
        "jejucafe",
        "제주공항근처숙소",
        "제주루프탑카페",
        "서귀포라운지",
        "서귀포레스토랑",
        "제주연동카페",
        "테이크아웃",
        "파운드케이크",
        "북클래스",
        "비건찻집",
        "수제차",
        "애월아빠들",
        "러디스",
        "서귀포바다",
        "제주수제맥주",
        "서귀포찻집",
        "제주도찻집",
        "btb",
        "베이크띵스베럴",
        "제과점",
        "공항카페",
        "오라동카페",
        "주차",
        "용담카페",
        "제주공항소품샵",
        "법환술집",
        "법환카페",
        "법환포구",
        "브루잉커피",
        "법환동카페",
        "밀크티빙수",
        "블루베리빙수",
        "제주녹차빙수",
        "제주빙수",
        "서호동카페",
        "라떼맛집",
        "병맥주",
        "붕어빵",
        "스페샬티커피",
        "프릳츠커피",
        "비건메뉴",
        "썸오브어스커피",
        "제주용담동카페",
        "달곰푸딩",
        "제주먹거리",
        "제주푸딩",
        "용연구름다리",
        "제주시야경",
        "녹차아이스크림",
        "아이스아메리카노",
        "유기농유자차",
        "서점",
        "인도",
        "귤양갱",
        "귤에이드",
        "귤농장",
        "제주도루프탑카페",
        "제주도오션뷰카페",
        "제주갤러리카페",
        "오등동카페",
        "도남동꽃집",
        "도남동카페",
        "제주꽃집",
        "제주이색카페",
        "커스텀케이크",
        "제주도핫플레이스",
        "제주시커피맛집",
        "제주다쿠아즈맛집",
        "빈티지카페",
        "제주즐길거리",
        "가족친구와함께",
        "셜록홈즈방탈출",
        "연인과함께",
        "방탈출카페",
        "룸술집",
        "보드게임",
        "제주핫플레이스",
        "제주시그니처",
        "제주추천",
        "제주탑동",
        "카페송키",
        "센잇",
        "센잇과자",
        "센잇화석과자",
        "해산물과자",
        "화석과자",
        "동문시장카페",
        "관덕정카페",
        "탑동카페",
        "자키커피",
        "심리상담카페",
        "에스프레소바",
        "크림브륄레",
        "푸딩",
        "돌창고",
        "이도초근처카페",
        "제주까망곰",
        "쿠킹클레스",
        "글루텐프리",
        "쌀디저트",
        "쌀케이크",
        "구남동카페",
        "바닐라크림슈페너",
        "젤라또",
        "에그타르트맛집",
        "수제마카롱전문",
        "캐릭터마카롱",
        "포켓몬마카롱",
        "제주인제카페",
        "핸드드립카페",
        "꽃",
        "꽃집",
        "이벤트선물",
        "서귀포시카페",
        "제주딸기케이크",
        "제주브라이덜샤워",
        "제주생일케이크",
        "요거트",
        "제주수제쿠키",
        "아라동쿠키",
        "제주쿠키맛집",
        "브루잉",
        "아라동커피숍",
        "제주라떼맛집",
        "제주아라동카페",
        "제주크림라떼",
        "로스팅커피",
        "제주로스터리",
        "랑그드샤",
        "마들렌크림마들렌",
        "제주수제청수제잼",
        "쿠키박스선물세트",
        "구제주커피맛집",
        "제주커피바",
        "미트파이",
        "동홍동카페",
        "서홍동카페",
        "양식카페",
        "포토스팟",
        "북유럽풍",
        "프로방스풍",
        "아라동브런치",
        "귤라떼",
        "천지연카페",
        "건강음료",
        "감귤밭카페",
        "제주쌀빵",
        "코삿",
        "한라산뷰카페",
        "서귀포샌드위치",
        "서귀포샐러드",
        "게스트바리스타",
        "김사홍",
        "김사홍바리스타",
        "블루리본",
        "커피템플",
        "삼화지구카페",
        "팥빙수맛집",
        "카페맛집",
        "제주케이크맛집",
        "윈드1947",
        "서귀다원",
        "제주귤카페",
        "딸기빙수",
        "서귀포빙수",
        "야생화카페",
        "돈내코카페",
        "상효동카페",
        "고양이북카페",
        "고양이천국",
        "제주도고양이천국",
        "다저트카페",
        "오브제주",
        "서귀포여행지",
        "제주도신촌",
        "제주조천카페",
        "바베큐",
        "서귀포바베큐",
        "바베큐플래터",
        "제주도바베큐",
        "와흘354",
        "제주동쪽애견카페",
        "제주반려견카페",
        "제주도라이더카페",
        "제주라이더카페",
        "제주바이크카페",
        "제주오후다섯시",
        "백패킹",
        "하이킹",
        "행동식",
        "간소한여행",
        "Cayl",
        "함덕가볼만한곳",
        "함덕카페추천",
        "그릭요거트",
        "제주그릭요거트",
        "제주요거트",
        "공방카페",
        "함덕해수욕장카페",
        "과일카페",
        "남원커피",
        "서귀포커피",
        "위미커피",
        "약차카페",
        "귤카페",
        "도르래카페",
        "콘테나앙빵",
        "야외애견카페",
        "제주애견운동장",
        "보라크림라떼",
        "제주당근케이크",
        "서귀포위미맛집",
        "서귀포소품샵",
        "위미카페",
        "북촌플레이스",
        "올드북촌",
        "제주북스테이",
        "제주북촌카페",
        "반미샌드위치",
        "테라리움",
        "반려동물동반가능",
        "콘센트없는매장",
        "맷돌커피",
        "치즈바",
        "남원해수풀장",
        "놀이공원",
        "서귀포아이랑",
        "제주유아식",
        "말차라떼맛집",
        "제주녹차밭",
        "제주말차",
        "선흘베이커리카페",
        "선흘소품샵",
        "선흘식료품샵",
        "선흘와인보틀샵",
        "제주타셴북",
        "제주조용한카페",
        "남원읍맛집",
        "남원맛집",
        "남원큰엉",
        "보늬밤",
        "남원카페",
        "레스빠스",
        "반려동물간식",
        "김녕소품샵",
        "수박스무디",
        "토이카페",
        "#꿩만두",
        "#꿩엿.감귤피자",
        "#보름왓인근",
        "#사월의꿩카페",
        "#스카이워터쇼입",
        "모멘커리커피",
        "바다뷰카페",
        "수제쌀빵",
        "요거트스무디",
        "레몬일레븐",
        "소노캄제주카페",
        "제주레몬카페",
        "성읍카페",
        "무끈모루",
        "비자림로",
        "안돌오름",
        "송당무끈모루",
        "뷰좋은카페",
        "김녕해수욕장카페",
        "복합문화공간",
        "우도땅콩아이스크",
        "제주도아이스크림",
        "제주월정리카페",
        "단체좌석",
        "바다가보이는카페",
        "바다전망",
        "월정리",
        "제주스페셜티커피",
        "월정리베이커리",
        "월정리해변카페",
        "월정카페",
        "잼카페",
        "소품카페",
        "옷카페",
        "카페치즈태비",
        "리치망고",
        "망고",
        "과일티",
        "실외수영장",
        "디카페인",
        "제주민속촌",
        "커피족욕",
        "반려동물카페",
        "비자림카페",
        "Cafe",
        "Coffee",
        "Dacone",
        "Dessert",
        "Jeju",
        "귀여운카페",
        "치즈냥형제",
        "구좌소품샵",
        "평대소품샵",
        "평대해변카페",
        "평대리브런치카페",
        "평대리카페",
        "로봇스퀘어",
        "월정리부근",
        "제주도표선카페",
        "제주민속촌카페",
        "제주산애플망고",
        "카페추천",
        "삼달리카페",
        "성산읍카페",
        "제주도빵맛집",
        "바닷가카페",
        "포토존카페",
        "표선카페추천",
        "펜션형민박",
        "껍질째짠밀감주스",
        "유기농당근주스",
        "제주당근주스맛집",
        "삼달카페",
        "성산커피맛집",
        "티백커피",
        "폴란드가정식빵",
        "클램차우더",
        "성산브런치",
        "수제샌드위치",
        "요거트볼",
        "핸드드드립커피",
        "공주풍",
        "카페탕탕",
        "탕탕",
        "하도리철새도래지",
        "제주구좌카페",
        "제주올레길카페",
        "하도카페",
        "바보나무사진카페",
        "사진찍어주는카페",
        "제주도사진명소",
        "제주도이벤트",
        "제주도이쁜카페",
        "부띠끄카페",
        "모뉴에트",
        "종달리",
        "구좌북카페",
        "제주도북카페",
        "종달리북카페",
        "종달리디저트",
        "종달리소품",
        "종달리와인",
        "제주자전거카페",
        "제주해변카페",
        "청귤에이드",
        "티라미수",
        "성산카페추천",
        "제주도대형카페",
        "봄그리고가을맛집",
        "성산일출봉브런치",
        "제주성산브런치",
        "명상센터",
        "성산요가원",
        "성산와인",
        "광치기해변",
        "섭지코지",
        "라틴바",
        "도넛맛집",
        "분위기깡패",
        "사진찍기좋은곳",
        "성산일출봉우도뷰",
        "제주프리미엄재료",
        "편안한",
        "제주우도여행",
        "훈데르트바서",
        "검멀레",
        "달그리안",
        "목장갑서비스",
        "제주도배낚시",
        "차귀도",
        "차귀도배낚시",
        "제2한라호",
        "물레체험",
        "제주도서쪽여행",
        "제주도전기자전거",
        "제주도전동바이크",
        "제주서쪽코스",
        "금능서핑",
        "애월서핑",
        "협재서핑",
        "협재해수욕장서핑",
        "제주돌고래",
        "제주돌고래요트",
        "제주요트투어",
        "도자기공예체험",
        "스테인드글라스",
        "조식팬션",
        "핸드페인팅체험",
        "공방노나메",
        "사계리해변",
        "원데이체험",
        "할링클래스",
        "프리다이빙",
        "나무반지",
        "레이저각인",
        "제주반지공방",
        "제주반지만들기",
        "제주그림",
        "제주화실",
        "유화그림",
        "제주미술",
        "제주도클래스",
        "애월체험",
        "제주관광지",
        "제주엑티비티",
        "제주힐링",
        "서핑보드대여",
        "수영복",
        "제주서핑강습",
        "자격증클래스",
        "제주중문서핑",
        "중문해수욕장서핑",
        "서귀포서핑",
        "제주도프리다이빙",
        "제주도돌고래",
        "제주도요트투어",
        "승마장",
        "선상낚시",
        "공항자전거",
        "오토바이대여",
        "오토바이렌탈",
        "제주도오토바이",
        "캔들만들기",
        "플라워클래스",
        "제주도캔들공방",
        "제주만들기",
        "제주캔들공방",
        "제주키즈클래스",
        "다이빙",
        "서귀포다이빙",
        "스쿠버",
        "제주도리본공예",
        "제주도선물포장",
        "제주선물포장",
        "제주시리본공예",
        "제주시선물포장",
        "미술공방",
        "수채화미술",
        "유화미술",
        "서귀포스킨스쿠버",
        "서귀포체험다이빙",
        "스킨스쿠버강습",
        "제주스킨스쿠버",
        "제주체험다이빙",
        "서귀포자전거대여",
        "전기스쿠터대여",
        "서귀포나무공방",
        "원두",
        "원목소품",
        "핸드드립용품",
        "핸드드립체험",
        "미싱공방",
        "소잉공방",
        "제로웨이스트",
        "서프앤조이",
        "제주도서핑샵",
        "제주서핑샵",
        "민화수업",
        "제주도스킨스쿠버",
        "제주도체험다이빙",
        "제주스쿠버다이빙",
        "골프리조트",
        "9홀골프장",
        "비누답례품",
        "수제비누",
        "제주비누",
        "제주비누공방",
        "제주비누답례품",
        "케익공방",
        "좌대낚시",
        "비누만들기",
        "천연비누공방",
        "키즈클래스",
        "화장품만들기",
        "실내놀이터",
        "가죽공예",
        "천연화장품",
        "잠수함관광",
        "겹벚꽃명소",
        "사회적기업",
        "왕초보승마체험",
        "제주말타는곳",
        "제주속성승마",
        "제주승마",
        "제주승마체험",
        "관광호텔",
        "사우나",
        "연회장",
        "조식서비스",
        "제주녹차",
        "패들보트",
        "레진공예",
        "종이공예체험",
        "월정리서핑",
        "월정서핑",
        "제주서핑캠프",
        "전동킥보드",
        "전동킥보드대여",
        "수상스키",
        "제주동쪽여행",
        "제주스쿠터여행",
        "제주자전거여행",
        "하도리서핑",
        "제주도패들보드",
        "하도서핑",
        "카라반",
        "커플룸",
        "스킨스쿠버다이빙",
        "제주도다이빙",
    ]

class PlaceInfoScraper:
    def __init__(self):
        self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
        self.driver.implicitly_wait(5)

    def get_place_info(self, address):
        self.driver.get(address)
        sleep(2)

        html = self.driver.page_source
        soup = BeautifulSoup(html, "html.parser")
        location_evaluation = soup.select("div.location_evaluation > a.link_evaluation")
        comment_count = 0
        review_count = 0
        for ele in location_evaluation:
            if ele["data-target"] == "comment":
                comment_count = int(ele["data-cnt"])
            elif ele["data-target"] == "review":
                review_count = int(ele["data-cnt"])
        return comment_count, review_count

    def get_place_data(self, address):
        result = {}
        self.driver.get(address)
        sleep(2)

        html = self.driver.page_source
        soup = BeautifulSoup(html, "html.parser")

        # 유효한 주소인지 확인
        if soup.select_one("div.wrap_mapdetail.no_result") is not None:
            return None

        # 장소 이미지 url
        img_url = soup.select_one("div.details_present > a.link_present > span.bg_present")
        if img_url is not None:
            img_url = img_url["style"][24:-2]

        # 태그
        link_tag = soup.select("div.location_detail > div.txt_tag > span.tag_g > a.link_tag")
        ar = []
        if link_tag is not None:
            for tag in link_tag:
                ar.append(tag.text[1:])
        tag_df = pd.DataFrame(ar, columns=["tag"])

        # 리뷰
        location_evaluation = soup.select("div.location_evaluation > a.link_evaluation")
        comment_count = 0
        for ele in location_evaluation:
            if ele["data-target"] == "comment":
                comment_count = int(ele["data-cnt"])

        while comment_count > 3:
            button = self.driver.find_element(By.CLASS_NAME, 'link_more')
            sleep(0.5)
            btn_text = button.text

            if btn_text in ["메뉴 더보기", "상품정보 더보기", "코스 더보기"]:
                button = self.driver.find_elements(By.CLASS_NAME, 'link_more')
                sleep(0.5)
                btn_text = button[1].text
                button = button[1]

            if btn_text == "후기 접기":
                break
            button.click()

        html = self.driver.page_source
        soup = BeautifulSoup(html, "html.parser")
        reviews = soup.select("ul.list_evaluation > li")
        created_date = []
        score = []
        for review in reviews:
            time_write = review.select_one("div.unit_info > span.time_write").text
            rating_per = review.select_one("div.star_info > div > span > span")["style"][6:-2]
            user_rating = int(int(rating_per) / 20)  # 유저별 별점
            created_date.append(time_write)
            score.append(user_rating)

        ar = np.array([score, created_date]).T
        review_df = pd.DataFrame(ar, columns=["score", "created_date"])

        result["img_url"] = img_url
        result["tag"] = tag_df
        result["review"] = review_df

        # print(result)
        return result


if __name__ == "__main__":
    print_tag_count()



